on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install
        run:  yarn
      - name: build
        run:  make build
      - name: test
        run:  make test
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
